# Generated by Django 5.1.1 on 2025-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatureworkflow',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted_by_clerk', 'Accepted by Clerk'), ('rejected_by_clerk', 'Rejected by Clerk'), ('accepted', 'Accepted'), ('rejected', 'Rejected by signature validation'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
