# Generated by Django 5.1.1 on 2025-04-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_delete_documentsignprocess'),
        ('signature_workflows', '0002_alter_signatureworkflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatureworkflow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='documents.document'),
        ),
    ]
