# Generated by Django 5.1.1 on 2025-04-09 16:52

import signature_workflows.encoding
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature_workflows', '0003_alter_signatureworkflow_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatureworkflow',
            name='form_data',
            field=models.JSONField(default=dict, encoder=signature_workflows.encoding.PrettyJSONEncoder),
        ),
        migrations.AlterField(
            model_name='signatureworkflow',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted_by_clerk', 'Awaiting Signature'), ('rejected_by_clerk', 'Rejected by Clerk'), ('accepted', 'Accepted'), ('rejected', 'Rejected by signature validation'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
