# Generated by Django 5.1.1 on 2025-04-09 16:55

import django.db.models.deletion
import signature_workflows.encoding
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_historicaldocument'),
        ('signature_workflows', '0004_alter_signatureworkflow_form_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSignatureWorkflow',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted_by_clerk', 'Awaiting Signature'), ('rejected_by_clerk', 'Rejected by Clerk'), ('accepted', 'Accepted'), ('rejected', 'Rejected by signature validation'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('rejected_signatures', models.IntegerField(default=0)),
                ('form_data', models.JSONField(default=dict, encoder=signature_workflows.encoding.PrettyJSONEncoder)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical signature workflow',
                'verbose_name_plural': 'historical signature workflows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
