# Generated by Django 5.1.1 on 2025-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature_workflows', '0005_historicalsignatureworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignatureworkflow',
            name='document_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signatureworkflow',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='completed_documents/'),
        ),
    ]
