# Generated by Django 5.1.1 on 2025-03-15 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignProcess',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='signature', serialize=False, to='documents.document')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted_by_clerk', 'Accepted by Clerk'), ('rejected_by_clerk', 'Rejected by Clerk'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rejected_signatures', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/signature_files/')),
                ('features', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_ms', models.IntegerField()),
            ],
        ),
    ]
