# Generated by Django 5.1.1 on 2025-04-05 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsignprocess',
            name='form_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='documentsignprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
