# Generated by Django 5.1.1 on 2025-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='time_sec',
            new_name='time_ms',
        ),
        migrations.AddField(
            model_name='signature',
            name='features',
            field=models.BinaryField(default=b'asd'),
            preserve_default=False,
        ),
    ]
