# Generated by Django 5.1.1 on 2025-04-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_documentsignprocess_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSignProcess',
        ),
    ]
