# Generated by Django 5.1.1 on 2025-03-15 17:33

import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('template', models.FileField(upload_to='document_templates/', validators=[documents.validators.validate_html_extension])),
            ],
        ),
    ]
