# Generated by Django 5.1.1 on 2025-02-27 13:30

import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.FileField(upload_to='document_templates/', validators=[documents.validators.validate_html_extension]),
        ),
    ]
