# Generated by Django 5.1.1 on 2025-04-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsignprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSignProcess',
        ),
    ]
