# Generated by Django 5.1.1 on 2025-03-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentform',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='documents.document'),
        ),
    ]
