# Generated by Django 5.1.1 on 2025-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_alter_documentform_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='tooltip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('tel', 'Phone'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons')], max_length=20),
        ),
    ]
