# Generated by Django 5.1.1 on 2025-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_formfield_tooltip_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='tooltip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
