# Generated by Django 5.1.1 on 2025-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_alter_formfield_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field_id')},
        ),
    ]
