# Generated by Django 5.1.1 on 2025-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_formfield_field_id_alter_formfield_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
